# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
#  vmImage: ubuntu-latest
name: default

#  container: ubuntu:16.04


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'build'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    date
    uname -a
    echo pwd
    pwd
    echo "ls -lrt /home/vsts/work/1/s/bin/Release/net6.0/"
    ls -lrt /home/vsts/work/1/s/bin/Release/net6.0/
  displayName: 'Run a multi-line script'
